import React from 'react'
import fl5 from '../../assets/fl5.jpg'


const Fac5Updated = () => {
  return (
    <>
      <div className='bg-gray-200 py-5 px-5 md:px-12 lg:px-28'>
        <div className='text-center my-24'>
          <h1 className='text-2xl sm:text-5xl font-semibold max-w-[700px] mx-auto mt-36 pb-2'>
            Oxyfuel Welding
          </h1>
        </div>
      </div>
      <div className='mx-5 max-w-[800px] md:mx-auto mt-[-100px] mb-10'>
        <img src={fl5} className='h-80 border-4 border-white mx-auto' alt="GMAW" />
        <h1 className='my-8 text-[26px] font-semibold'>About Oxyfuel Welding:</h1>
        <p>Oxyfuel Welding (OFW), also known as Oxy-Acetylene Welding, is a traditional welding process that uses a flame generated by burning a mixture of oxygen and a fuel gas (typically acetylene) to melt and join metals. It is widely used in metal fabrication, repair work, and artistic applications due to its simplicity and portability.</p>
        <h3 className='my-5 text-[18px] font-semibold'>How Oxyfuel Welding Works</h3>
        <p className='my-3'>OFW generates heat by combusting a fuel gas with oxygen, creating a high-temperature flame. The flame melts the base metal, and filler metal can be added if needed to form a strong joint. No external electrical power is required, making it a versatile process for both workshop and field applications.</p>
        <h3 className='my-5 text-[18px] font-semibold'>Key Features of OFW</h3>
        <p className='my-3'>1. Equipment</p>
        <p className='my-3'>The primary equipment required for OFW includes:</p>
        <p className='my-3'>Oxygen Cylinder: Supplies pure oxygen to support combustion.</p>
        <p className='my-3'>Fuel Gas Cylinder: Supplies a combustible gas (commonly acetylene, propane, or hydrogen).</p>
        <p className='my-3'>Regulators: Control the gas pressure from the cylinders.</p>
        <p className='my-3'>Hoses and Torch: Deliver and mix the gases to create a controlled flame.</p>
        <p className='my-3'>Filler Rod (Optional): Provides additional material for joint reinforcement.</p>

        <h3 className='my-5 text-[18px] font-semibold'>Conclusion</h3>
        <p className='my-3'>OFW is a simple, portable, and effective welding process, ideal for applications where electricity is not available. While it has been largely replaced by modern arc welding methods in industrial applications, it remains a valuable technique for repair work, brazing, and artistic metalwork. Its flexibility and ease of use ensure its continued relevance in various industries.</p>
        
        <div className='my-24'>
            <a href="https://en.wikipedia.org/wiki/Oxy-fuel_welding_and_cutting#:~:text=In%20oxy%2Dfuel%20welding%2C%20a,the%20metals%20to%20be%20welded." className='text-black font-semibold my-4 underline' target='_blank'>Link for the whole article </a>
        </div>
      </div>

    </>
  )
}

export default Fac5Updated
