// import React from 'react';
// import fl5 from '../../assets/fl5.jpg';

// const Fac5Updated = () => {
//   return (
//     <>
//       {/* Top Section with Background Image */}
//       <div className='relative bg-gray-200 pt-28 pb-5 px-5 md:px-12 lg:px-28'>
//         {/* Background Image with Red Tint */}
//         <div className='absolute inset-0 w-full h-full overflow-hidden'>
//           <img 
//             src={fl5} 
//             className='w-full h-full object-cover opacity-20 filter grayscale' 
//             alt="Background" 
//           />
//           <div className="absolute inset-0 bg-red-500 opacity-20"></div> {/* Red Tint */}
//         </div>

//         {/* Content on Top */}
//         <div className='relative text-center my-24'>
//           <h1 className='text-2xl sm:text-5xl font-semibold max-w-[700px] mx-auto mt-36 pb-2'>
//             Oxyfuel Welding
//           </h1>
//         </div>
//       </div>

//       {/* Main Image in Foreground */}
//       <div className='relative flex justify-center -mt-20 z-0'>
//         <img 
//           src={fl5} 
//           className='h-80 border-4 border-gray-700 shadow-xl' 
//           alt="OFW Machine" 
//         />
//       </div>

//       {/* Description Section */}
//       <div className='px-5 md:px-12 lg:px-28 mt-10'>
//         <h1 className='text-[26px] font-semibold'>About Oxyfuel Welding:</h1>
//         <p className='my-3'>Oxyfuel Welding (OFW), also known as Oxy-Acetylene Welding, is a traditional welding process that uses a flame generated by burning a mixture of oxygen and a fuel gas (typically acetylene) to melt and join metals. It is widely used in metal fabrication, repair work, and artistic applications due to its simplicity and portability.</p>

//         <h3 className='mt-5 text-[18px] font-semibold'>How Oxyfuel Welding Works</h3>
//         <p className='my-3'>OFW generates heat by combusting a fuel gas with oxygen, creating a high-temperature flame. The flame melts the base metal, and filler metal can be added if needed to form a strong joint. No external electrical power is required, making it a versatile process for both workshop and field applications.</p>

//         <h3 className='mt-5 text-[18px] font-semibold'>Key Features of OFW</h3>
//         <ul className='list-disc pl-5 my-3'>
//           <li><strong>Oxygen Cylinder:</strong> Supplies pure oxygen to support combustion.</li>
//           <li><strong>Fuel Gas Cylinder:</strong> Supplies a combustible gas (commonly acetylene, propane, or hydrogen).</li>
//           <li><strong>Regulators:</strong> Control the gas pressure from the cylinders.</li>
//           <li><strong>Hoses and Torch:</strong> Deliver and mix the gases to create a controlled flame.</li>
//           <li><strong>Filler Rod (Optional):</strong> Provides additional material for joint reinforcement.</li>
//         </ul>

//         <h3 className='mt-5 text-[18px] font-semibold'>Conclusion</h3>
//         <p className='my-3'>OFW is a simple, portable, and effective welding process, ideal for applications where electricity is not available. While it has been largely replaced by modern arc welding methods in industrial applications, it remains a valuable technique for repair work, brazing, and artistic metalwork. Its flexibility and ease of use ensure its continued relevance in various industries.</p>

//         <div className='my-8'>
//           <a 
//             href="https://en.wikipedia.org/wiki/Oxy-fuel_welding_and_cutting#:~:text=In%20oxy%2Dfuel%20welding%2C%20a,the%20metals%20to%20be%20welded." 
//             className='text-red-600 font-semibold underline' 
//             target='_blank'
//           >
//             Read More on Wikipedia
//           </a>
//         </div>
//       </div>
//     </>
//   );
// };

// export default Fac5Updated;

// import React from 'react';
// import fl4 from '../../assets/fl4.png';

// const Fac4Updated = () => {
//   return (
//     <>
//       {/* Top Section with Background Image */}
//       <div className='relative bg-gray-200 pt-28 pb-5 px-5 md:px-12 lg:px-28'>
//         {/* Background Image with Red Tint */}
//         <div className='absolute inset-0 w-full h-full overflow-hidden'>
//           <img 
//             src={fl4} 
//             className='w-full h-full object-cover opacity-20 filter grayscale' 
//             alt="Background" 
//           />
//           <div className="absolute inset-0 bg-red-500 opacity-20"></div> {/* Red Tint */}
//         </div>

//         {/* Content on Top */}
//         <div className='relative text-center my-24'>
//           <h1 className='text-2xl sm:text-5xl font-semibold max-w-[700px] mx-auto mt-36 pb-2'>
//             Gas Tungsten Arc Welding
//           </h1>
//         </div>
//       </div>

//       {/* Main Image in Foreground */}
//       <div className='relative flex justify-center -mt-20 z-0'>
//         <img 
//           src={fl4} 
//           className='h-80 border-4 border-gray-700 shadow-xl' 
//           alt="GTAW Machine" 
//         />
//       </div>

//       {/* Description Section */}
//       <div className='px-5 md:px-12 lg:px-28 mt-10'>
//         <h1 className='text-[26px] font-semibold'>About GTAW:</h1>
//         <p className='my-3'>Gas Tungsten Arc Welding (GTAW), also known as Tungsten Inert Gas (TIG) welding, is a precise and high-quality welding process commonly used in industries requiring clean and strong welds. It is widely applied in aerospace, automotive, and stainless steel fabrication due to its superior control and minimal spatter.</p>

//         <h3 className='mt-5 text-[18px] font-semibold'>How GTAW Works</h3>
//         <p className='my-3'>GTAW utilizes a non-consumable tungsten electrode to create an electric arc that melts the base metal. An external shielding gas, typically argon or helium, protects the weld pool from atmospheric contamination. Filler metal may be added manually, depending on the application, allowing for precise control over the welding process.</p>

//         <h3 className='mt-5 text-[18px] font-semibold'>Key Features of GTAW</h3>
//         <ul className='list-disc pl-5 my-3'>
//           <li><strong>Welding Power Source:</strong> Provides a stable electrical current (AC or DC) for welding.</li>
//           <li><strong>Tungsten Electrode:</strong> Creates the arc and withstands high temperatures without melting.</li>
//           <li><strong>Welding Torch:</strong> Holds the tungsten electrode and directs shielding gas to the weld zone.</li>
//           <li><strong>Shielding Gas Supply:</strong> Prevents oxidation and contamination of the weld (usually argon or helium).</li>
//           <li><strong>Foot Pedal or Hand Control:</strong> Adjusts the heat input for precise welding control.</li>
//         </ul>

//         <h3 className='mt-5 text-[18px] font-semibold'>Conclusion</h3>
//         <p className='my-3'>GTAW is a highly precise and versatile welding process, ideal for applications requiring superior weld quality and minimal distortion. Its ability to produce clean, high-strength welds makes it essential in industries where precision is critical, such as aerospace, medical equipment, and stainless steel fabrication.</p>

//         <div className='my-8'>
//           <a 
//             href="https://en.wikipedia.org/wiki/Gas_tungsten_arc_welding" 
//             className='text-red-600 font-semibold underline' 
//             target='_blank'
//           >
//             Read More on Wikipedia
//           </a>
//         </div>
//       </div>
//     </>
//   );
// };

// export default Fac4Updated;

import React from 'react';
import fl5 from '../../assets/fl5.jpg';
import Accordion from '@mui/material/Accordion';
import AccordionSummary from '@mui/material/AccordionSummary';
import AccordionDetails from '@mui/material/AccordionDetails';
import ExpandMoreIcon from '@mui/icons-material/ExpandMore';
import Button from '@mui/material/Button';

const Fac5Updated = () => {
  return (
    <>
      {/* Background Section */}
      <div className="relative bg-gray-200 pt-28 pb-5 px-5 md:px-12 lg:px-28">
        <div className="absolute inset-0 w-full h-full overflow-hidden">
          <img
            src={fl5}
            className="w-full h-full object-cover opacity-20 filter grayscale"
            alt="3-Axis Welding Manipulator Background"
          />
          <div className="absolute inset-0 bg-blue-500 opacity-20"></div>
        </div>

        <div className="relative text-center my-24">
          <h1 className="text-2xl sm:text-5xl font-semibold max-w-[700px] mx-auto pb-2">
         Oxyfuel Welding
          </h1>
        </div>
      </div>

      {/* Image Section */}
      <div className="relative flex justify-center -mt-20 z-0">
        <img
          src={fl5}
          className="h-80 border-4 border-gray-700 shadow-xl rounded-lg"
          alt="3-Axis Welding Manipulator"
        />
      </div>

     {/* Introduction Section */}
<div className="px-6 md:px-12 lg:px-24 my-8">
  <h2 className="text-3xl font-bold text-gray-900 mb-4">Introduction to Oxyfuel Welding (OFW)</h2>
  <p className="text-gray-700 leading-relaxed">
    <strong>Oxyfuel Welding (OFW)</strong>, also referred to as <strong>Oxy-Acetylene Welding</strong>, is a traditional gas welding process that uses a flame produced by burning a fuel gas (typically acetylene) with oxygen.
    It is a versatile and portable technique often used for cutting, welding, brazing, and heating metals—especially in maintenance, repair, and metal art applications.
  </p>
</div>

{/* Accordion Section */}
<div className="px-6 md:px-12 lg:px-24">

  {/* Working */}
  <Accordion className="!my-0 !rounded-none !border-b border-gray-300">
    <AccordionSummary expandIcon={<ExpandMoreIcon />}>
      <p className="font-semibold text-lg">1. How it Works</p>
    </AccordionSummary>
    <AccordionDetails>
      <p className="text-gray-700">
        OFW uses a flame created by burning a mixture of oxygen and a fuel gas (commonly acetylene) to melt the base metal and allow a weld to form. 
        <br /><br />
        Components involved:
        <br />
        • <strong>Oxygen cylinder</strong> – Supplies pure oxygen to intensify the flame<br />
        • <strong>Fuel gas cylinder</strong> – Acetylene, propane, or other gas for combustion<br />
        • <strong>Welding torch</strong> – Mixes and controls gas flow and flame<br />
        • <strong>Filler rod</strong> – Optional metal rod to add material to the joint<br /><br />
        Flame types:
        <br />
        • <strong>Neutral flame</strong> – Ideal for welding (balanced oxygen/fuel)<br />
        • <strong>Carburizing flame</strong> – For processes like brazing<br />
        • <strong>Oxidizing flame</strong> – Used for cutting or welding brass
      </p>
    </AccordionDetails>
  </Accordion>

  {/* Applications */}
  <Accordion className="!my-0 !rounded-none !border-b border-gray-300">
    <AccordionSummary expandIcon={<ExpandMoreIcon />}>
      <p className="font-semibold text-lg">2. Applications</p>
    </AccordionSummary>
    <AccordionDetails>
      <ul className="list-disc pl-6 text-gray-700">
        <li><strong>General repair and maintenance</strong> work</li>
        <li><strong>Metal sculpture</strong> and artistic fabrication</li>
        <li><strong>Farm and construction equipment</strong> repair</li>
        <li><strong>Plumbing and HVAC</strong> brazing tasks</li>
        <li><strong>Cutting and heating</strong> operations on mild steel</li>
        <li><strong>Training and education</strong> due to simplicity and visibility</li>
      </ul>
    </AccordionDetails>
  </Accordion>

  {/* Usage in Industries */}
  <Accordion className="!my-0 !rounded-none !border-b border-gray-300">
    <AccordionSummary expandIcon={<ExpandMoreIcon />}>
      <p className="font-semibold text-lg">3. Usage in Industries</p>
    </AccordionSummary>
    <AccordionDetails>
      <p className="text-gray-700">
        Though less common in high-production manufacturing today, OFW is still used in:
        <br /><br />
        • <strong>Automotive repair shops</strong> – For heating and brazing<br />
        • <strong>Metal art and sculpture studios</strong><br />
        • <strong>Plumbing and pipe fitting</strong> – Especially for copper brazing<br />
        • <strong>Rural or field-based maintenance</strong> – Portable and independent of electricity<br />
        • <strong>Educational institutes</strong> – Ideal for basic welding training
      </p>
    </AccordionDetails>
  </Accordion>

  {/* Defects & Challenges */}
  <Accordion className="!my-0 !rounded-none !border-b border-gray-300">
    <AccordionSummary expandIcon={<ExpandMoreIcon />}>
      <p className="font-semibold text-lg">4. Defects and Challenges</p>
    </AccordionSummary>
    <AccordionDetails>
      <ul className="list-disc pl-6 text-gray-700">
        <li><strong>Lower precision</strong> compared to modern arc welding methods</li>
        <li><strong>Not suitable</strong> for high-strength or reactive metals</li>
        <li><strong>Safety hazards</strong> due to flammable gases and open flames</li>
        <li><strong>Slower process</strong> for thick sections</li>
        <li><strong>Limited penetration</strong> on thicker materials</li>
        <li><strong>Potential oxidation</strong> if flame is not neutral</li>
      </ul>
    </AccordionDetails>
  </Accordion>

  {/* Cost Effectiveness */}
  <Accordion className="!my-0 !rounded-none !border-b border-gray-300">
    <AccordionSummary expandIcon={<ExpandMoreIcon />}>
      <p className="font-semibold text-lg">5. Cost Effectiveness</p>
    </AccordionSummary>
    <AccordionDetails>
      <p className="text-gray-700">
        OFW is one of the most cost-effective welding methods in terms of:
        <br /><br />
        • <strong>Low equipment costs</strong> – Basic torches and regulators are affordable<br />
        • <strong>No electricity required</strong> – Ideal for remote or mobile jobs<br />
        • <strong>Multi-purpose use</strong> – Cutting, welding, brazing, and heating<br />
        • <strong>Inexpensive to maintain</strong> – Simple and rugged setup<br />
        However, it is <strong>less efficient for industrial-scale production</strong> compared to MIG/TIG.
      </p>
    </AccordionDetails>
  </Accordion>

  {/* Best Practices */}
  <Accordion className="!my-0 !rounded-none !border-b border-gray-300">
    <AccordionSummary expandIcon={<ExpandMoreIcon />}>
      <p className="font-semibold text-lg">6. Best Practices</p>
    </AccordionSummary>
    <AccordionDetails>
      <ul className="list-disc pl-6 text-gray-700">
        <li>Always use a <strong>neutral flame</strong> for welding to avoid oxidation</li>
        <li><strong>Check for leaks</strong> in hoses and regulators before starting</li>
        <li>Keep cylinders <strong>upright and secured</strong> during use</li>
        <li>Use <strong>correct tip size</strong> for the metal thickness</li>
        <li><strong>Preheat thicker sections</strong> to avoid cracking</li>
        <li>Store fuel gases and oxygen <strong>separately and safely</strong></li>
      </ul>
    </AccordionDetails>
  </Accordion>
</div>



      {/* Learn More Button */}
      <div className="flex justify-center my-8">
        <Button
          variant="contained"
          color="primary"
          href="https://www.uti.edu/blog/welding/oxy-acetylene-welding"
          target="_blank"
          size="large"
        >
          Learn More About Oxyfuel Welding
        </Button>
      </div>
    </>
  );
};

export default Fac5Updated;
