import React from 'react';
import fl5 from '../../assets/fl5.jpg';

const Fac5Updated = () => {
  return (
    <>
      {/* Top Section with Background Image */}
      <div className='relative bg-gray-200 pt-28 pb-5 px-5 md:px-12 lg:px-28'>
        {/* Background Image with Red Tint */}
        <div className='absolute inset-0 w-full h-full overflow-hidden'>
          <img 
            src={fl5} 
            className='w-full h-full object-cover opacity-20 filter grayscale' 
            alt="Background" 
          />
          <div className="absolute inset-0 bg-red-500 opacity-20"></div> {/* Red Tint */}
        </div>

        {/* Content on Top */}
        <div className='relative text-center my-24'>
          <h1 className='text-2xl sm:text-5xl font-semibold max-w-[700px] mx-auto mt-36 pb-2'>
            Oxyfuel Welding
          </h1>
        </div>
      </div>

      {/* Main Image in Foreground */}
      <div className='relative flex justify-center -mt-20 z-0'>
        <img 
          src={fl5} 
          className='h-80 border-4 border-gray-700 shadow-xl' 
          alt="OFW Machine" 
        />
      </div>

      {/* Description Section */}
      <div className='px-5 md:px-12 lg:px-28 mt-10'>
        <h1 className='text-[26px] font-semibold'>About Oxyfuel Welding:</h1>
        <p className='my-3'>Oxyfuel Welding (OFW), also known as Oxy-Acetylene Welding, is a traditional welding process that uses a flame generated by burning a mixture of oxygen and a fuel gas (typically acetylene) to melt and join metals. It is widely used in metal fabrication, repair work, and artistic applications due to its simplicity and portability.</p>

        <h3 className='mt-5 text-[18px] font-semibold'>How Oxyfuel Welding Works</h3>
        <p className='my-3'>OFW generates heat by combusting a fuel gas with oxygen, creating a high-temperature flame. The flame melts the base metal, and filler metal can be added if needed to form a strong joint. No external electrical power is required, making it a versatile process for both workshop and field applications.</p>

        <h3 className='mt-5 text-[18px] font-semibold'>Key Features of OFW</h3>
        <ul className='list-disc pl-5 my-3'>
          <li><strong>Oxygen Cylinder:</strong> Supplies pure oxygen to support combustion.</li>
          <li><strong>Fuel Gas Cylinder:</strong> Supplies a combustible gas (commonly acetylene, propane, or hydrogen).</li>
          <li><strong>Regulators:</strong> Control the gas pressure from the cylinders.</li>
          <li><strong>Hoses and Torch:</strong> Deliver and mix the gases to create a controlled flame.</li>
          <li><strong>Filler Rod (Optional):</strong> Provides additional material for joint reinforcement.</li>
        </ul>

        <h3 className='mt-5 text-[18px] font-semibold'>Conclusion</h3>
        <p className='my-3'>OFW is a simple, portable, and effective welding process, ideal for applications where electricity is not available. While it has been largely replaced by modern arc welding methods in industrial applications, it remains a valuable technique for repair work, brazing, and artistic metalwork. Its flexibility and ease of use ensure its continued relevance in various industries.</p>

        <div className='my-8'>
          <a 
            href="https://en.wikipedia.org/wiki/Oxy-fuel_welding_and_cutting#:~:text=In%20oxy%2Dfuel%20welding%2C%20a,the%20metals%20to%20be%20welded." 
            className='text-red-600 font-semibold underline' 
            target='_blank'
          >
            Read More on Wikipedia
          </a>
        </div>
      </div>
    </>
  );
};

export default Fac5Updated;
